export default{
    products:[
        {
            _id:'1',
            name:'Aceite Premium',
            category:'Aceites',
            image:'https://plazavea.vteximg.com.br/arquivos/ids/16382488-1000-1000/20281564.jpg',
            price:60,
            brand:'Primor',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'2',
            name:'Menestras',
            category:'Aceites',
            image:'https://web.ins.gob.pe/sites/default/files/noticias/MENESTRAS.jpg',
            price:60,
            brand:'Primor',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'3',
            name:'Aceite Premium',
            category:'Ceviche',
            image:'https://comidasperuanas.net/wp-content/uploads/2020/12/Ceviche-de-Caballa.jpg',
            price:60,
            brand:'Primor',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'4',
            name:'Aceite Premium',
            category:'Aceites',
            image:'https://plazavea.vteximg.com.br/arquivos/ids/16382488-1000-1000/20281564.jpg',
            price:60,
            brand:'Primor',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'5',
            name:'Arroz Costeño',
            category:'Arroz',
            image:'https://plazavea.vteximg.com.br/arquivos/ids/554165-1000-1000/641425.jpg',
            price:60,
            brand:'Costeño',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'6',
            name:'Aceite Premium',
            category:'Aceites',
            image:'https://plazavea.vteximg.com.br/arquivos/ids/16382488-1000-1000/20281564.jpg',
            price:60,
            brand:'Primor',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        }
    ]
}